### ISSUE TITLE
Fix project setup

### ISSUE THREAD

**Issue by pstorch** [androidoma/Bahnhofsfotos#1]
At the moment Android Studio isn't able to properly import the project from the gradle files.

@androidoma I'm on it and send a Pull Request soon ;)

**Comment by androidoma** [comment]
Super,  Danke!!! 

Am 23. August 2016 22:14:24 MESZ, schrieb Peter Storch <notifications@github.com>:
>At the moment Android Studio isn't able to properly import the project
>from the gradle files.
>
>@androidoma I'm on it and send a Pull Request soon ;)
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/androidoma/Bahnhofsfotos/issues/1

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.
